### ISSUE TITLE
Adding fixOrientation code

### ISSUE THREAD

**Issue by furkanarabaci** [smartface/sample-video-quality#1]
After converting to mp4, iOS will capture video as oriented to the right. To fix that, this snippet needs to be added into the project.

```
//@ts-ignore
Multimedia.ios._fixVideoOrientation({
    videoFile: convertedVideo,
    onCompleted: ({ video: orientationFixedVideo }) => {
        this.convertedVideoFile = orientationFixedVideo;
        this.convertVideoToBase64(orientationFixedVideo);
        // Your code, whatever
    },
    onFailure: () => {
    }
});
```
You might want to cover that with System.OS check.

This snippet is not necessary if the video isn't going to be converted to mp4.

**Comment by berkbaski** [comment]
@furkanarabaci we have merged the branch related to this issue.
