### ISSUE TITLE
Quality tweak devices

### ISSUE THREAD

**Issue by furkanarabaci** [smartface/sample-video-quality#2]
As we discussed, some devices behave differently on quality change. it might be good idea to either implement or add it as a hint into the project.

Here is the low quality devices

```
const lowQualityAndroidDevices = [
    'xiaomi',
    'huawei'
];
```

When quality is set to LOW, it reduces to 144p, making them almost unnoticeable. We might warn the people who come across this.

Here is an example code 

```
lowQualityAndroidDevices.some((device) => Hardware.brandName.toLowerCase().includes(device.toLowerCase())) ?
    Multimedia.VideoQuality.HIGH :
    Multimedia.VideoQuality.LOW,
```

**Comment by berkbaski** [comment]
@furkanarabaci we have merged the branch related to this issue.
